/**
 * @module enrichment/EnrichmentStore.legacy.test
 * Proves that an enrichments.sqlite written by the previous better-sqlite3
 * implementation opens and reads correctly with the node:sqlite implementation.
 *
 * The fixture `__fixtures__/enrichments.better-sqlite3.sqlite` was generated by
 * the better-sqlite3 13.0.3 build of EnrichmentStore (WAL mode, same schema).
 */

import { copyFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { EnrichmentStore } from './EnrichmentStore';

const fixture = join(
  dirname(fileURLToPath(import.meta.url)),
  '__fixtures__',
  'enrichments.better-sqlite3.sqlite',
);

const LEGACY_CREATED_AT = '2026-09-27T02:39:20.401Z';

let stateDir: string;
let store: EnrichmentStore;

beforeEach(() => {
  stateDir = mkdtempSync(join(tmpdir(), 'enrichment-legacy-'));
  copyFileSync(fixture, join(stateDir, 'enrichments.sqlite'));
  store = new EnrichmentStore(stateDir);
});

afterEach(() => {
  store.close();
  rmSync(stateDir, { recursive: true, force: true });
});

describe('EnrichmentStore (legacy better-sqlite3 database)', () => {
  it('lists every legacy path', () => {
    expect(store.list()).toEqual([
      '/new/moved.txt',
      '/notes/alpha.txt',
      'd:/docs/report.md',
    ]);
  });

  it('reads legacy metadata, including merged and moved rows', () => {
    expect(store.get('D:\\Docs\\Report.md')).toEqual({
      domain: 'docs',
      tags: ['a', 'b'],
      category: 'reports',
    });
    expect(store.get('/notes/alpha.txt')).toEqual({
      priority: 1,
      nested: { ok: true },
    });
    expect(store.get('/new/moved.txt')).toEqual({ moved: 'yes' });
    expect(store.get('/old/moved.txt')).toBeNull();
    expect(store.get('/deleted.txt')).toBeNull();
  });

  it('merges into, moves and deletes legacy rows', () => {
    store.set('d:/docs/report.md', { category: 'final', extra: true });
    expect(store.get('d:/docs/report.md')).toEqual({
      domain: 'docs',
      tags: ['a', 'b'],
      category: 'final',
      extra: true,
    });

    store.move('/notes/alpha.txt', '/notes/beta.txt');
    expect(store.get('/notes/alpha.txt')).toBeNull();
    expect(store.get('/notes/beta.txt')).toEqual({
      priority: 1,
      nested: { ok: true },
    });

    store.delete('/new/moved.txt');
    expect(store.list()).toEqual(['/notes/beta.txt', 'd:/docs/report.md']);
  });

  it('keeps WAL mode and preserves legacy timestamps', () => {
    store.set('d:/docs/report.md', { touched: true });
    store.close();

    const db = new DatabaseSync(join(stateDir, 'enrichments.sqlite'));
    try {
      const mode = db.prepare('PRAGMA journal_mode').get() as {
        journal_mode: string;
      };
      expect(mode.journal_mode).toBe('wal');

      const row = db
        .prepare(
          'SELECT created_at, updated_at FROM enrichments WHERE path = ?',
        )
        .get('d:/docs/report.md') as { created_at: string; updated_at: string };
      expect(row.created_at).toBe(LEGACY_CREATED_AT);
      expect(row.updated_at > LEGACY_CREATED_AT).toBe(true);
    } finally {
      db.close();
    }

    // Reopen so afterEach close has a live store.
    store = new EnrichmentStore(stateDir);
  });
});
